spring.application.name=compra

# Conexion a Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.etimaxesrtgrgtnalbmr
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de conexiones a Supabase
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del microservicio
server.port=8081

# Microsoft Entra ID / Spring Cloud Azure
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=d788e613-d97d-4ea3-a9d9-61589d1a6c72
spring.cloud.azure.active-directory.profile.tenant-id=54b79561-1edb-49d8-9906-2cd26284e9b6
spring.cloud.azure.active-directory.app-id-uri=api://d788e613-d97d-4ea3-a9d9-61589d1a6c72